#!/bin/sh

if [ -z "$1" ]; then
  cmd=ls
else
  cmd=$1
fi

set -e
base=`git rev-parse --show-toplevel`
issues=$base/.issues

git stash >/dev/null
case $cmd in

  init)
    if [ -d $issues ]; then
      echo $issues directory already exists
      exit
    fi
    mkdir $issues
    echo 0 >$issues/seq
    git add $issues/seq
    echo $issues/'*' >> $base/.gitignore # FIXME: if not already in there
    git add $base/.gitignore
    git commit -m 'git issues initialized'
    ;;

  new)
    id=`cat $issues/seq`
    id=$((id + 1))
    echo $id > $issues/seq
    git add $issues/seq
    ticket=`mktemp /tmp/issue-$id-XXXXXX`
    echo "=== issue title ===" >>$ticket
    echo "" >>$ticket
    echo "describe the new issue here" >>$ticket
    sensible-editor $ticket
    mv $ticket $issues/issue-$id
    ticket=$issues/issue-$id
    git add $ticket
    git commit -m "issue #$id created"
    ;;

  ls)
    id=`cat $issues/seq`
    for i in `seq $id`
    do
      echo -n "#$i "
      cat $issues/issue-$i
      echo
    done
    ;;

esac
git stash pop >/dev/null 2>&1

